# discussion.yml
name: 機能に関する議論
description: 機能に関する議論はこちら
title: 'Discussion: '

body:
  - type: textarea
    id: topic
    attributes:
      label: 議題
      description: |
        議論のテーマや話題を簡潔に記載してください。
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 詳細
      description: |
        議論の詳細や背景情報を記載してください。
    validations:
      required: true
      
  - type: textarea
    id: suggestions
    attributes:
      label: 提案
      description: |
        議論に関する提案や意見を自由に記載してください。
