# new_feature.yml
name: 新機能の追加
description: 新しい機能の提案はこちら
title: 'Feature: '
body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: |
        新機能の概要を記載してください。
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: 提案の動機
      description: |
        新機能の提案の動機や利点を記載してください。
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: 実装案
      description: |
        新機能の実装方法やアイデアを記載してください。
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: |
        代替案やその他の考えがあれば記載してください。